"""create production and inventory

Revision ID: 4780a09ff307
Revises: 745e0269acc3
Create Date: 2026-09-01 16:16:49.576044

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4780a09ff307"
down_revision: str | Sequence[str] | None = "745e0269acc3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "warehouses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "production_batches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("warehouse_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=15, scale=3), nullable=False),
        sa.Column("package_count", sa.Integer(), nullable=True),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column(
            "produced_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "package_count IS NULL OR package_count > 0",
            name="ck_production_batches_package_count_positive",
        ),
        sa.CheckConstraint(
            "quantity > 0", name="ck_production_batches_quantity_positive"
        ),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["warehouse_id"], ["warehouses.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_production_batches_created_by_id"),
        "production_batches",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_production_batches_product_id"),
        "production_batches",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_production_batches_warehouse_id"),
        "production_batches",
        ["warehouse_id"],
        unique=False,
    )
    op.create_table(
        "stock_movements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("warehouse_id", sa.Integer(), nullable=False),
        sa.Column(
            "movement_type",
            sa.Enum(
                "production",
                "purchase",
                "delivery",
                "write_off",
                "return",
                "adjustment",
                name="stock_movement_type",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("quantity_delta", sa.Numeric(precision=15, scale=3), nullable=False),
        sa.Column("production_batch_id", sa.Integer(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.CheckConstraint(
            "quantity_delta <> 0", name="ck_stock_movements_quantity_delta_non_zero"
        ),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["production_batch_id"], ["production_batches.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"], ["warehouses.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stock_movements_created_by_id"),
        "stock_movements",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_movements_product_id"),
        "stock_movements",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_movements_production_batch_id"),
        "stock_movements",
        ["production_batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_movements_warehouse_id"),
        "stock_movements",
        ["warehouse_id"],
        unique=False,
    )
    op.drop_constraint(op.f("product_type"), "products", type_="check")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        op.f("product_type"),
        "products",
        "product_type::text = ANY (ARRAY['raw_material'::character varying, 'finished_good'::character varying, 'packaging'::character varying]::text[])",
    )
    op.drop_index(op.f("ix_stock_movements_warehouse_id"), table_name="stock_movements")
    op.drop_index(
        op.f("ix_stock_movements_production_batch_id"), table_name="stock_movements"
    )
    op.drop_index(op.f("ix_stock_movements_product_id"), table_name="stock_movements")
    op.drop_index(
        op.f("ix_stock_movements_created_by_id"), table_name="stock_movements"
    )
    op.drop_table("stock_movements")
    op.drop_index(
        op.f("ix_production_batches_warehouse_id"), table_name="production_batches"
    )
    op.drop_index(
        op.f("ix_production_batches_product_id"), table_name="production_batches"
    )
    op.drop_index(
        op.f("ix_production_batches_created_by_id"), table_name="production_batches"
    )
    op.drop_table("production_batches")
    op.drop_table("warehouses")
    # ### end Alembic commands ###
