"""create customers and deliveries

Revision ID: 4be212f3f828
Revises: 4780a09ff307
Create Date: 2026-09-01 22:58:58.740701

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4be212f3f828"
down_revision: str | Sequence[str] | None = "4780a09ff307"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_customers_code"), "customers", ["code"], unique=True)
    op.create_index(op.f("ix_customers_name"), "customers", ["name"], unique=False)
    op.create_table(
        "deliveries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("warehouse_id", sa.Integer(), nullable=False),
        sa.Column("courier_id", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column(
            "delivered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(["courier_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["warehouse_id"], ["warehouses.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deliveries_courier_id"), "deliveries", ["courier_id"], unique=False
    )
    op.create_index(
        op.f("ix_deliveries_created_by_id"),
        "deliveries",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deliveries_customer_id"), "deliveries", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_deliveries_warehouse_id"), "deliveries", ["warehouse_id"], unique=False
    )
    op.create_table(
        "delivery_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("delivery_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=15, scale=3), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.CheckConstraint("quantity > 0", name="ck_delivery_items_quantity_positive"),
        sa.CheckConstraint(
            "unit_price >= 0", name="ck_delivery_items_unit_price_non_negative"
        ),
        sa.ForeignKeyConstraint(["delivery_id"], ["deliveries.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "delivery_id", "product_id", name="uq_delivery_items_delivery_product"
        ),
    )
    op.create_index(
        op.f("ix_delivery_items_delivery_id"),
        "delivery_items",
        ["delivery_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_delivery_items_product_id"),
        "delivery_items",
        ["product_id"],
        unique=False,
    )
    op.add_column(
        "stock_movements", sa.Column("delivery_item_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_stock_movements_delivery_item_id"),
        "stock_movements",
        ["delivery_item_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_stock_movements_delivery_item_id_delivery_items",
        "stock_movements",
        "delivery_items",
        ["delivery_item_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_stock_movements_delivery_item_id_delivery_items",
        "stock_movements",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_stock_movements_delivery_item_id"), table_name="stock_movements"
    )
    op.drop_column("stock_movements", "delivery_item_id")
    op.drop_index(op.f("ix_delivery_items_product_id"), table_name="delivery_items")
    op.drop_index(op.f("ix_delivery_items_delivery_id"), table_name="delivery_items")
    op.drop_table("delivery_items")
    op.drop_index(op.f("ix_deliveries_warehouse_id"), table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_customer_id"), table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_created_by_id"), table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_courier_id"), table_name="deliveries")
    op.drop_table("deliveries")
    op.drop_index(op.f("ix_customers_name"), table_name="customers")
    op.drop_index(op.f("ix_customers_code"), table_name="customers")
    op.drop_table("customers")
    # ### end Alembic commands ###
