"""create suppliers and purchases

Revision ID: 787595b09f69
Revises: 4be212f3f828
Create Date: 2026-09-11 16:23:35.896705

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "787595b09f69"
down_revision: str | Sequence[str] | None = "4be212f3f828"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "suppliers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_suppliers_code"), "suppliers", ["code"], unique=True)
    op.create_index(op.f("ix_suppliers_name"), "suppliers", ["name"], unique=False)
    op.create_table(
        "purchases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("supplier_id", sa.Integer(), nullable=False),
        sa.Column("warehouse_id", sa.Integer(), nullable=False),
        sa.Column("invoice_number", sa.String(length=100), nullable=True),
        sa.Column(
            "purchased_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["warehouse_id"], ["warehouses.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "supplier_id", "invoice_number", name="uq_purchases_supplier_invoice_number"
        ),
    )
    op.create_index(
        op.f("ix_purchases_created_by_id"), "purchases", ["created_by_id"], unique=False
    )
    op.create_index(
        op.f("ix_purchases_supplier_id"), "purchases", ["supplier_id"], unique=False
    )
    op.create_index(
        op.f("ix_purchases_warehouse_id"), "purchases", ["warehouse_id"], unique=False
    )
    op.create_table(
        "purchase_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("purchase_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=15, scale=3), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.CheckConstraint("quantity > 0", name="ck_purchase_items_quantity_positive"),
        sa.CheckConstraint(
            "unit_price >= 0", name="ck_purchase_items_unit_price_non_negative"
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["purchase_id"], ["purchases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "purchase_id", "product_id", name="uq_purchase_items_purchase_product"
        ),
    )
    op.create_index(
        op.f("ix_purchase_items_product_id"),
        "purchase_items",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_items_purchase_id"),
        "purchase_items",
        ["purchase_id"],
        unique=False,
    )
    op.add_column(
        "stock_movements", sa.Column("purchase_item_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_stock_movements_purchase_item_id"),
        "stock_movements",
        ["purchase_item_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_stock_movements_purchase_item_id_purchase_items",
        "stock_movements",
        "purchase_items",
        ["purchase_item_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_stock_movements_purchase_item_id_purchase_items",
        "stock_movements",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_stock_movements_purchase_item_id"), table_name="stock_movements"
    )
    op.drop_column("stock_movements", "purchase_item_id")
    op.drop_index(op.f("ix_purchase_items_purchase_id"), table_name="purchase_items")
    op.drop_index(op.f("ix_purchase_items_product_id"), table_name="purchase_items")
    op.drop_table("purchase_items")
    op.drop_index(op.f("ix_purchases_warehouse_id"), table_name="purchases")
    op.drop_index(op.f("ix_purchases_supplier_id"), table_name="purchases")
    op.drop_index(op.f("ix_purchases_created_by_id"), table_name="purchases")
    op.drop_table("purchases")
    op.drop_index(op.f("ix_suppliers_name"), table_name="suppliers")
    op.drop_index(op.f("ix_suppliers_code"), table_name="suppliers")
    op.drop_table("suppliers")
    # ### end Alembic commands ###
